<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>To Do List</title>
		<meta name="viewport" content="width=device-width, user-scalable=no">
		<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="PUBLIC/STYLES/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="PUBLIC/STYLES/bootstrap-theme.min.css">
		<link rel="stylesheet" type="text/css" href="PUBLIC/STYLES/style.css">
		<script type="text/javascript" src="PUBLIC/SCRIPTS/jquery.min.js"></script>
		<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
		<script type="text/javascript" src="PUBLIC/SCRIPTS/bootstrap.min.js"></script>
		<script type="text/javascript" src="PUBLIC/SCRIPTS/script.js"></script>
	</head>
<body>
	<div class="row">
		<?php require('APPS/header.php'); ?>
	</div>
	<div class="row">
		<?php require('APPS/content.php'); ?>
		<div class="scrollup"></div>
	</div>
	<div class="row">
		<?php require('APPS/footer.php'); ?>
	</div>
</body>
</html>
