<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>tchat</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link rel="stylesheet" href="PUBLIC/STYLE/style.css">
</head>
<body>
	<div class="container">
		<div class="row">
			<?php require('APPS/header.php'); ?>
		</div>
		<div class="row">
			<?php require('APPS/content.php'); ?>
		</div>
		<div class="row">
			<?php require('APPS/footer.php'); ?>
		</div>
	</div>
</body>
</html>