<div class="message">
	<div class="">
		<input type="hidden" name="IdUser" value="<?=htmlentities($_SESSION['id'])?>">
		<input type="text" class="js_in form_create_message form-control" id="create_message" name="content" value="" autofocus autocomplete="off">
		<button type="submit" class="form_create_message btn btn-success" name="action" value="create_message" >Envoyer</button>
	</div>
</div>



  


